name: marvel
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  dartz: ^0.10.1
  dio: ^5.0.3
  equatable: ^2.0.5
  logger: ^1.3.0

dev_dependencies:
  http_mock_adapter: ^0.4.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
